
apiVersion: v1
kind: Secret
metadata:
  name: usersapi-secrets
type: Opaque
stringData:
  CONNECTION_STRING: Host=users-db;Database=users;Username=postgres;Password=postgres
  JWT_SECRET: dev_secret_change_me
