
apiVersion: v1
kind: Secret
metadata:
  name: usersapi-secrets
type: Opaque
stringData:
  CONNECTION_STRING: "Server=sqlserver;Database=usersdb;User Id=sa;Password=Strong!Passw0rd;TrustServerCertificate=True"
  JWT_KEY: "SUA_CHAVE_SEGURA_AQUI"
